#!/bin/bash
# Update package lists
apt-get update
apt-get install -y nginx
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
/etc/init.d/nginx restart
echo "Hello World!" > /var/www/html/index.html
chmod 644 /var/www/html/index.html
